version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment: 
        SA_PASSWORD: "@Password123"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Developer"
    ports: ["1433:1433"]
  # mssqltools:
  #   image: mcr.microsoft.com/mssql-tools
  #   depends_on:
  #       - sqlserver
  #   volumes:
  #       - ./db-create.sql:/tmp/db-create.sql                  
  #   command: /bin/bash -c "sleep 10 && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P @Password123 -d master -i /tmp/db-create.sql"
  pedidos.api:
    image: ${DOCKER_REGISTRY-}pedidosapi
    build: .
    ports: ["8081:8081"]
    depends_on: 
        - sqlserver 
